### ISSUE TITLE
Pale Moon compatibility?

### ISSUE THREAD

**Issue by Accoun** [sblask/firefox-tab-deque#5]
As someone who moved from Opera 12 to Firefox, I liked the add-on. However, with some of FF's recent changes (and worse performance than what I remember from Opera) I'm trying out Pale Moon and I'm thinking of sticking with it.
However, this add-on isn't compatible with it. I'm not sure how much work would making it work with PM's SDK be, but I'd love to see it fixed.

**Comment by sblask** [comment]
If it's really not compatible, I will probably not work on it. However, the problem could just be that they changed the GUID (see https://addons.palemoon.org/resources/incompatible/)

So what you can try is to clone this repository, change this line:
https://github.com/sblask/firefox-tab-deque/blob/master/install.rdf#L16 to the value you can find here: https://forum.palemoon.org/viewtopic.php?f=1&t=5440 and then use the pack.sh (basically just zipping up all files) to create an xpi. You should then be able to install it from Pale Moon. (In Firefox it's enough to drag and drop the file into any of its windows)

**Comment by sblask** [comment]
I didn't hear back on this, so I will just close it...
